<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       

        // Chèn dữ liệu vào bảng products
        DB::table('products')->insert([
            [
                'ProductId' => 8,
                'name' => 'BMW 3 Series',
                'BrandId' => 6,
                'price' => 900000000.00,
                'quantity' => 2,
                'image_url' => 'images/bmw3series.png',
                'description' => 'BMW 3 Series mới sở hữu cá tính thể thao năng động...',
                'color' => 'red',
                'created_at' => Carbon::parse('2024-11-23 09:48:19'),
                'updated_at' => Carbon::parse('2024-11-23 09:48:19'),
            ],
            [
                'ProductId' => 9,
                'name' => 'BMW 2 Series',
                'BrandId' => 6,
                'price' => 800000000.00,
                'quantity' => 2,
                'image_url' => 'images/bmw3series.png',
                'description' => 'BMW 3 Series mới sở hữu cá tính thể thao năng động...',
                'color' => 'red',
                'created_at' => Carbon::parse('2024-11-23 09:48:55'),
                'updated_at' => Carbon::parse('2024-11-23 09:48:55'),
            ],
            [
                'ProductId' => 10,
                'name' => 'BMW 4 Series',
                'BrandId' => 6,
                'price' => 700000000.00,
                'quantity' => 2,
                'image_url' => 'images/bmw3series.png',
                'description' => 'BMW 3 Series mới sở hữu cá tính thể thao năng động...',
                'color' => 'red',
                'created_at' => Carbon::parse('2024-11-23 09:59:12'),
                'updated_at' => Carbon::parse('2024-11-23 09:59:12'),
            ],
            [
                'ProductId' => 11,
                'name' => 'BMW 4 Series',
                'BrandId' => 6,
                'price' => 500000000.00,
                'quantity' => 2,
                'image_url' => 'images/bmw3series.png',
                'description' => 'BMW 3 Series mới sở hữu cá tính thể thao năng động...',
                'color' => 'red',
                'created_at' => Carbon::parse('2024-11-23 10:00:36'),
                'updated_at' => Carbon::parse('2024-11-23 10:00:36'),
            ],
            [
                'ProductId' => 12,
                'name' => 'BMW 1 Series',
                'BrandId' => 6,
                'price' => 800000000.00,
                'quantity' => 1,
                'image_url' => 'images/bmw3series.png',
                'description' => 'BMW 3 Series mới sở hữu cá tính thể thao năng động...',
                'color' => 'red',
                'created_at' => Carbon::parse('2024-11-23 10:01:00'),
                'updated_at' => Carbon::parse('2024-11-23 10:01:00'),
            ],
            [
                'ProductId' => 13,
                'name' => 'C-Class 2022',
                'BrandId' => 7,
                'price' => 960000000.00,
                'quantity' => 2,
                'image_url' => 'images/Mec C-Class 2022.jpg',
                'description' => 'C-class 2022 thế hệ mới (mã W206) bán tại Việt Nam...',
                'color' => 'red',
                'created_at' => Carbon::parse('2024-11-23 10:06:00'),
                'updated_at' => Carbon::parse('2024-11-23 10:06:00'),
            ],
            [
                'ProductId' => 14,
                'name' => 'GLB 2021',
                'BrandId' => 7,
                'price' => 1100000000.00,
                'quantity' => 3,
                'image_url' => 'images/GLB 2021.png',
                'description' => 'C-class 2022 thế hệ mới (mã W206) bán tại Việt Nam...',
                'color' => 'red',
                'created_at' => Carbon::parse('2024-11-23 10:06:50'),
                'updated_at' => Carbon::parse('2024-11-23 10:06:50'),
            ],
            [
                'ProductId' => 15,
                'name' => 'E-Class 2021',
                'BrandId' => 7,
                'price' => 1500000000.00,
                'quantity' => 1,
                'image_url' => 'images/GLB 2021.png',
                'description' => 'Năm 1996, nhà máy đặt tại Gò Vấp, TP HCM của hãng ...',
                'color' => 'red',
                'created_at' => Carbon::parse('2024-11-23 10:08:59'),
                'updated_at' => Carbon::parse('2024-11-23 10:08:59'),
            ],
            [
                'ProductId' => 16,
                'name' => 'BR-V',
                'BrandId' => 2,
                'price' => 400000000.00,
                'quantity' => 2,
                'image_url' => 'images/Honda.png',
                'description' => 'Bạn có thể lựa chọn những phụ kiện trang trí giúp ...',
                'color' => 'black',
                'created_at' => Carbon::parse('2024-11-23 10:13:08'),
                'updated_at' => Carbon::parse('2024-11-23 10:13:08'),
            ],
            [
                'ProductId' => 17,
                'name' => 'Wigo G 405 triệu',
                'BrandId' => 1,
                'price' => 405000000.00,
                'quantity' => 2,
                'image_url' => 'images/toyota.png',
                'description' => 'Tại Triển lãm Ô tô năm 2017, Toyota Wigo lần đầu t...',
                'color' => 'red',
                'created_at' => Carbon::parse('2024-11-23 10:15:19'),
                'updated_at' => Carbon::parse('2024-11-23 10:15:19'),
            ],
            [
                'ProductId' => 18,
                'name' => 'STORMTRAK',
                'BrandId' => 3,
                'price' => 990000000.00,
                'quantity' => 2,
                'image_url' => 'images/bmw1.png',
                'description' => 'Khoản đặt cọc có thể được hoàn/hủy trong trường hợ...',
                'color' => 'black',
                'created_at' => Carbon::parse('2024-11-23 10:17:07'),
                'updated_at' => Carbon::parse('2024-11-23 10:20:57'),
            ],
            [
                'ProductId' => 19,
                'name' => '911 Carrera GTS Cabriolet',
                'BrandId' => 14,
                'price' => 5000000000.00,
                'quantity' => 2,
                'image_url' => 'images/porsche.png',
                'description' => '* Giá tiêu chuẩn bao gồm thuế nhập khẩu, thuế tiêu...',
                'color' => 'red',
                'created_at' => Carbon::parse('2024-11-23 10:18:53'),
                'updated_at' => Carbon::parse('2024-11-23 10:18:53'),
            ],
            [
                'ProductId' => 20,
                'name' => '911 Carrera 4',
                'BrandId' => 14,
                'price' => 900000000.00,
                'quantity' => 1,
                'image_url' => 'images/Porsche2.jpg',
                'description' => '* Giá tiêu chuẩn bao gồm thuế nhập khẩu, thuế tiêu...',
                'color' => 'red',
                'created_at' => Carbon::parse('2024-11-23 10:20:08'),
                'updated_at' => Carbon::parse('2024-11-23 10:20:08'),
            ],
            [
                'ProductId' => 21,
                'name' => '911 Carrera 4 Cabriolet',
                'BrandId' => 14,
                'price' => 800000000.00,
                'quantity' => 2,
                'image_url' => 'images/Porsche2.jpg',
                'description' => '* Giá tiêu chuẩn bao gồm thuế nhập khẩu, thuế tiêu...',
                'color' => 'red',
                'created_at' => Carbon::parse('2024-11-23 10:24:12'),
                'updated_at' => Carbon::parse('2024-11-23 10:24:12'),
            ],
            [
                'ProductId' => 22,
                'name' => '911 Carrera 4 GTS',
                'BrandId' => 14,
                'price' => 900000000.00,
                'quantity' => 3,
                'image_url' => 'images/Porsche2.jpg',
                'description' => '911 Carrera 4 GTS* Giá tiêu chuẩn bao gồm thuế nhậ...',
                'color' => 'red',
                'created_at' => Carbon::parse('2024-11-23 10:26:10'),
                'updated_at' => Carbon::parse('2024-11-23 10:26:10'),
            ],
            [
                'ProductId' => 23,
                'name' => 'adada',
                'BrandId' => 1,
                'price' => 2322423.00,
                'quantity' => 2,
                'image_url' => 'images/Porsche2.jpg',
                'description' => 'adasda',
                'color' => 'ada',
                'created_at' => Carbon::parse('2024-11-23 10:28:29'),
                'updated_at' => Carbon::parse('2024-11-23 10:28:29'),
            ],
            [
                'ProductId' => 24,
                'name' => 'ádaa',
                'BrandId' => 1,
                'price' => 21131313.00,
                'quantity' => 2,
                'image_url' => 'images/Porsche2.jpg',
                'description' => 'adasdsdasd',
                'color' => 'red',
                'created_at' => Carbon::parse('2024-11-23 10:29:50'),
                'updated_at' => Carbon::parse('2024-11-23 10:29:50'),
            ],
        ]);
    }
}
